version: "3.9"
services:
  grafana:
    image: grafana/grafana-oss
    ports: ["3000:3000"]

  prometheus:
    image: prom/prometheus
    volumes: ["./infra/prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]

