version: "3.8"
services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
      - "8002:8002"

  prometheus:
    image: prom/prometheus:v2.52.0
    restart: unless-stopped
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:11.0.0
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASS:-admin}"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana-data:


