# ── docker-compose.prod.yml ─────────────────────────────────────────────────
services:
  bot:
    image: royboi16/flash-green-poc:latest   # pull from Docker Hub
    restart: unless-stopped
    volumes:
      - ./data:/app/data:ro                  # mount your CSVs (read-only)
    ports:
      - "8000:8000"                          # Prometheus metrics
      - "8002:8002"                          # FastAPI health & PnL JSON

  prometheus:
    image: prom/prometheus:v2.52.0
    restart: unless-stopped
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:11.0.0
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASS:-admin}"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana-data:

